upstream django {
    server 127.0.0.1:8000;
}

server {
    server_name bxks.online www.bxks.online;

    # gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript image/svg+xml;

    client_max_body_size 100M;

    location /static/ {
        alias /root/django/staticfiles/;
    }

    location /media/ {
        alias /root/django/media/;
    }

    location / {
        proxy_pass http://django;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/bxks.online/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bxks.online/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}


server {
    if ($host = www.bxks.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = bxks.online) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name bxks.online www.bxks.online;
    return 404; # managed by Certbot




}