# Generated by Django 5.1.4 on 2025-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=32, verbose_name='身份')),
                ('password', models.CharField(max_length=64)),
                ('department', models.CharField(default='', max_length=32)),
                ('avatar', models.ImageField(blank=True, default='avatars/admin/default_avatar.png', null=True, upload_to='avatars/admin/')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男性'), ('女', '女性')], max_length=2, verbose_name='性别')),
                ('mobile', models.CharField(default='', max_length=11, verbose_name='手机')),
                ('marital_status', models.CharField(choices=[('未婚', '未婚'), ('已婚', '已婚')], max_length=2, verbose_name='婚姻状况')),
                ('education', models.CharField(max_length=50, verbose_name='学历+专业')),
                ('has_driver_license', models.CharField(choices=[('有', '有驾照'), ('无', '无驾照')], max_length=2, verbose_name='驾照')),
                ('special_skills', models.TextField(verbose_name='特长')),
                ('work_experience', models.TextField(verbose_name='工作经历')),
                ('current_address', models.CharField(blank=True, default='', max_length=10, verbose_name='现住所')),
                ('position', models.CharField(default='', max_length=20, verbose_name='应聘岗位')),
                ('expected_salary', models.CharField(max_length=20, verbose_name='期望薪资')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='一寸照')),
                ('resume_file', models.FileField(blank=True, default='', null=True, upload_to='resumes/', verbose_name='简历文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '求职者档案',
                'verbose_name_plural': '求职者档案',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='种类')),
                ('content', models.CharField(max_length=100, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='ContractLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('contract_file', models.FileField(upload_to='contractlabor/', verbose_name='劳动合同')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='ExplosiveInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_status', models.CharField(choices=[('出库', '出库'), ('入库', '入库')], default='出库', max_length=10, verbose_name='出入库状态')),
                ('project_department', models.CharField(max_length=100, verbose_name='项目部')),
                ('inventory_order_number', models.CharField(max_length=100, verbose_name='出入库单号')),
                ('warehouse_number', models.CharField(max_length=100, verbose_name='仓库编号')),
                ('technical_responsible_person', models.CharField(max_length=100, verbose_name='技术负责人')),
                ('custodian', models.CharField(max_length=100, verbose_name='保管员')),
                ('safety_Officer', models.CharField(default='', max_length=100, verbose_name='安全员')),
                ('blaster', models.CharField(default='', max_length=100, verbose_name='爆破员')),
                ('escort', models.CharField(max_length=100, verbose_name='押运员')),
                ('driver', models.CharField(max_length=100, verbose_name='驾驶员')),
                ('license_plate_number', models.CharField(max_length=100, verbose_name='车牌号？')),
                ('detonator_code', models.CharField(max_length=100, verbose_name='雷管编码')),
                ('explosive_quantity_90mm', models.IntegerField(default=0, verbose_name='90mm炸药(公斤)')),
                ('explosive_quantity_32mm', models.IntegerField(default=0, verbose_name='32mm炸药(公斤)')),
                ('detonating_device_quantity', models.IntegerField(default=0, verbose_name='起爆具(个)')),
                ('detonating_cord_length', models.IntegerField(default=0, verbose_name='导爆索(米)')),
                ('date', models.DateField(verbose_name='日期')),
            ],
        ),
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('front_image', models.ImageField(upload_to='ids/', verbose_name='人像面照片')),
                ('back_image', models.ImageField(upload_to='ids/', verbose_name='国徽面照片')),
                ('combined_image', models.ImageField(blank=True, null=True, upload_to='combined/', verbose_name='双面合成图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='JskjgQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=20)),
                ('tihao', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('options', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, verbose_name='ip')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ident', models.CharField(default='', max_length=32)),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('job', models.CharField(max_length=32, verbose_name='职位')),
                ('type', models.CharField(max_length=32, verbose_name='登入登出')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=20)),
                ('tihao', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('options', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tihao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('题号', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=100)),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedTu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(default='', max_length=100)),
                ('pdf_file', models.FileField(upload_to='tu/')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedZhaopian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='姓名')),
                ('photo', models.FileField(upload_to='photo/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_photo', models.ImageField(default='', upload_to='rotated/', verbose_name='排版')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ti_type', models.CharField(max_length=20)),
                ('tihao', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ident', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WxpzxQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(max_length=20)),
                ('tihao', models.CharField(max_length=20)),
                ('question', models.TextField()),
                ('options', models.CharField(max_length=200)),
                ('correct_answer', models.CharField(max_length=20)),
            ],
        ),
    ]
