# Generated by Django 5.1.4 on 2025-03-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_candidate_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplosiveStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=18, verbose_name='身份证号')),
                ('front_image', models.ImageField(upload_to='explosive_staff/', verbose_name='人像面照片')),
                ('back_image', models.ImageField(upload_to='explosive_staff/', verbose_name='国徽面照片')),
                ('combined_image', models.ImageField(upload_to='explosive_staff/', verbose_name='双面合成图')),
                ('photo', models.FileField(upload_to='explosive_staff/photo/', verbose_name='1寸照片')),
                ('typeset_photo', models.ImageField(upload_to='explosive_staff/', verbose_name='排版后照片')),
                ('no_crime', models.ImageField(upload_to='explosive_staff/', verbose_name='无犯罪证明')),
                ('graduation', models.ImageField(upload_to='explosive_staff/', verbose_name='毕业证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
