# Generated by Django 5.1.4 on 2025-03-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_explosivestaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedzhaopian',
            name='photo',
            field=models.FileField(upload_to='photo/', verbose_name='原始照片'),
        ),
        migrations.AlterField(
            model_name='uploadedzhaopian',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
