# Generated by Django 5.1.4 on 2025-03-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_uploadedzhaopian_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosivestaff',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='电话号'),
        ),
    ]
