# Generated by Django 5.1.4 on 2025-03-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_explosivestaff_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedzhaopian',
            name='blue_background',
            field=models.ImageField(blank=True, default='', null=True, upload_to='blue_background/', verbose_name='蓝底'),
        ),
        migrations.AddField(
            model_name='uploadedzhaopian',
            name='red_background',
            field=models.ImageField(blank=True, default='', null=True, upload_to='red_background/', verbose_name='红底'),
        ),
        migrations.AddField(
            model_name='uploadedzhaopian',
            name='white_background',
            field=models.ImageField(blank=True, default='', null=True, upload_to='white_background/', verbose_name='白底'),
        ),
    ]
