# Generated by Django 5.1.4 on 2025-03-20 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_uploadedzhaopian_blue_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosivestaff',
            name='bank_card_number',
            field=models.CharField(blank=True, default='', max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='银行卡号必须为16或19位数字', regex='^\\d{16}$|^\\d{19}$')], verbose_name='银行卡号'),
        ),
        migrations.AlterField(
            model_name='explosivestaff',
            name='graduation',
            field=models.ImageField(blank=True, null=True, upload_to='explosive_staff/', verbose_name='毕业证'),
        ),
        migrations.AlterField(
            model_name='explosivestaff',
            name='no_crime',
            field=models.ImageField(blank=True, null=True, upload_to='explosive_staff/', verbose_name='无犯罪证明'),
        ),
    ]
