# Generated by Django 5.1.4 on 2025-04-02 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_explosivestaff_bank_card_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeighingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='必须为"岩石"或12位纯数字', regex='^(岩石|\\d{12})$')], verbose_name='磅单号')),
                ('truck_driver', models.CharField(max_length=50, verbose_name='大车司机')),
                ('forklift_driver', models.CharField(max_length=50, verbose_name='铲车司机')),
                ('net_weight', models.IntegerField(verbose_name='矿石净重（kg）')),
                ('weight_photo', models.ImageField(upload_to='weighing_records/', verbose_name='称重单照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
