# Generated by Django 5.1.4 on 2025-04-21 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_weighingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='证书编号必须为13位数字', regex='^\\d{13}$')], verbose_name='证书编号')),
                ('name', models.CharField(max_length=4, verbose_name='姓名')),
                ('certificate_photo', models.ImageField(blank=True, null=True, upload_to='blasting_certificates/', verbose_name='爆破证照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爆破员证书',
                'verbose_name_plural': '爆破员证书',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='weighingrecord',
            name='weight_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='必须为岩石+10位纯数字 或 12位纯数字', regex='^(岩石\\d{10}|\\d{12})$')], verbose_name='磅单号'),
        ),
    ]
