# Generated by Django 5.1.4 on 2025-09-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_blastingcertificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explosiveinventoryitem',
            name='electronic_detonator_15m',
            field=models.IntegerField(default=0, verbose_name='15米电子雷管(发)'),
        ),
        migrations.AddField(
            model_name='explosiveinventoryitem',
            name='electronic_detonator_5m',
            field=models.IntegerField(default=0, verbose_name='5米电子雷管(发)'),
        ),
        migrations.AddField(
            model_name='explosiveinventoryitem',
            name='emulsion_explosive_32mm',
            field=models.IntegerField(default=0, verbose_name='32乳化(公斤)'),
        ),
        migrations.AddField(
            model_name='explosiveinventoryitem',
            name='powdery_explosive_box_2',
            field=models.IntegerField(default=0, verbose_name='2号粉箱(公斤)'),
        ),
        migrations.AddField(
            model_name='explosiveinventoryitem',
            name='sticky_explosive',
            field=models.IntegerField(default=0, verbose_name='粘药(公斤)'),
        ),
    ]
