# Generated by Django 5.1.4 on 2025-09-28 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_explosiveinventoryitem_electronic_detonator_15m_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='custodian',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='detonator_code',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='escort',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='explosive_quantity_32mm',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='explosive_quantity_90mm',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='inventory_order_number',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='license_plate_number',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='safety_Officer',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='technical_responsible_person',
        ),
        migrations.RemoveField(
            model_name='explosiveinventoryitem',
            name='warehouse_number',
        ),
    ]
