# Generated by Django 5.1.4 on 2026-05-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_remove_explosiveinventoryitem_custodian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=10, verbose_name='班次')),
                ('blaster', models.CharField(max_length=50, verbose_name='爆破员')),
                ('work_data', models.TextField(verbose_name='作业点数据(JSON)')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爆破作业登记',
                'verbose_name_plural': '爆破作业登记',
            },
        ),
    ]
