# Generated by Django 5.1.4 on 2026-05-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_blastingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=50, verbose_name='作业点负责人')),
                ('work_point', models.CharField(max_length=100, verbose_name='作业点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '作业点登记',
                'verbose_name_plural': '作业点登记',
            },
        ),
    ]
