# Generated by Django 5.1.4 on 2026-05-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_workpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blastingregistration',
            name='date',
            field=models.DateField(verbose_name='作业日期'),
        ),
    ]
