# Generated by Django 5.1.4 on 2026-05-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_blastingregistration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingregistration',
            name='usage_date',
            field=models.DateField(blank=True, null=True, verbose_name='使用日期'),
        ),
        migrations.AlterField(
            model_name='blastingregistration',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='日期'),
        ),
    ]
