# Generated by Django 5.1.4 on 2026-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_blastingregistration_usage_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='爆破员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '爆破员',
                'verbose_name_plural': '爆破员',
            },
        ),
    ]
