# Generated by Django 5.1.4 on 2026-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_blaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='人员')),
                ('location', models.CharField(max_length=100, verbose_name='地点')),
                ('date', models.CharField(max_length=20, verbose_name='日期')),
                ('detonator_count', models.IntegerField(default=0, verbose_name='雷管数')),
                ('explosive_count', models.IntegerField(default=0, verbose_name='炸药数(公斤)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '雷管炸药台账',
                'verbose_name_plural': '雷管炸药台账',
                'ordering': ['-created_at'],
            },
        ),
    ]
