# Generated by Django 5.1.4 on 2026-05-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_blastingsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingsummary',
            name='segments_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='分段数据'),
        ),
    ]
