# Generated by Django 5.1.4 on 2026-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_blastingsummary_segments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingsummary',
            name='blaster',
            field=models.CharField(blank=True, max_length=50, verbose_name='爆破员'),
        ),
    ]
