# Generated by Django 5.1.4 on 2026-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_blastingsummary_blaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingsummary',
            name='shift',
            field=models.CharField(blank=True, max_length=20, verbose_name='班次'),
        ),
    ]
