# Generated by Django 5.1.4 on 2026-05-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_blastingsummary_shift'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlastingRegistration',
        ),
        migrations.DeleteModel(
            name='WorkPoint',
        ),
    ]
