# Generated by Django 5.1.4 on 2026-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_delete_blastingregistration_delete_workpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastingSitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100, verbose_name='爆破地点')),
                ('photo', models.FileField(upload_to='blasting_site/', verbose_name='现场照片')),
                ('description', models.TextField(blank=True, null=True, verbose_name='现场描述')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '爆破现场记录',
                'verbose_name_plural': '爆破现场记录',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
