# Generated by Django 5.1.4 on 2026-05-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_blastingsitephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blastingsitephoto',
            name='description',
        ),
    ]
