# Generated by Django 5.1.4 on 2026-05-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_remove_blastingsitephoto_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingsitephoto',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='编号'),
        ),
    ]
