# Generated by Django 5.1.4 on 2026-05-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_blastingsitephoto_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastingsitephoto',
            name='blaster',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='爆破员'),
        ),
        migrations.AddField(
            model_name='blastingsitephoto',
            name='engineer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='工程师'),
        ),
        migrations.AddField(
            model_name='blastingsitephoto',
            name='safety_officer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='安全员'),
        ),
    ]
