# Generated by Django 5.1.4 on 2026-05-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_blastingsitephoto_blaster_blastingsitephoto_engineer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, unique=True, verbose_name='推送端点')),
                ('p256dh', models.TextField(blank=True, default='', verbose_name='p256dh密钥')),
                ('auth', models.TextField(blank=True, default='', verbose_name='auth密钥')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推送订阅',
                'verbose_name_plural': '推送订阅',
                'ordering': ['-created_at'],
            },
        ),
    ]
