# Generated by Django 5.1.4 on 2026-05-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.CharField(max_length=255, unique=True, verbose_name='推送端点'),
        ),
    ]
