# Generated by Django 5.1.4 on 2026-05-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0027_alter_pushsubscription_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='证件名称')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '证件类型',
                'verbose_name_plural': '证件类型',
                'db_table': 'app01_cert_type',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='部门')),
                ('status', models.CharField(choices=[('在职', '在职'), ('离职', '离职'), ('挂靠', '挂靠')], default='在职', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '人员信息',
                'verbose_name_plural': '人员信息',
                'db_table': 'app01_staff',
            },
        ),
        migrations.CreateModel(
            name='StaffCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_number', models.CharField(blank=True, max_length=64, verbose_name='证件编号')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='发证日期')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('status', models.CharField(choices=[('有效', '有效'), ('过期', '过期'), ('作废', '作废')], default='有效', max_length=16, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cert_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.certtype', verbose_name='证件类型')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.staff', verbose_name='人员')),
            ],
            options={
                'verbose_name': '人员证件',
                'verbose_name_plural': '人员证件',
                'db_table': 'app01_staff_cert',
            },
        ),
        migrations.CreateModel(
            name='StaffCertFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='certs/%Y/%m/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('正面', '正面'), ('反面', '反面'), ('扫描件', '扫描件'), ('其他', '其他')], default='其他', max_length=16, verbose_name='文件类型')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.staffcert', verbose_name='证件')),
            ],
            options={
                'verbose_name': '证件附件',
                'verbose_name_plural': '证件附件',
                'db_table': 'app01_staff_cert_file',
            },
        ),
    ]
