# Generated by Django 5.1.4 on 2026-05-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0028_certtype_staff_staffcert_staffcertfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedzhaopian',
            name='white_bg_single',
            field=models.ImageField(blank=True, default='', null=True, upload_to='white_bg_single/', verbose_name='白底一寸照'),
        ),
    ]
