# Generated by Django 5.1.4 on 2026-05-28 20:02

import app01.models.mine
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_uploadedzhaopian_white_bg_single'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('job_type', models.CharField(choices=[('爆破员', '爆破员'), ('安全员', '安全员'), ('工程师', '工程师')], default='爆破员', max_length=50, verbose_name='工种')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=app01.models.mine.photo_upload_path, verbose_name='一寸照片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '入井人员',
                'verbose_name_plural': '入井人员',
            },
        ),
    ]
