# Generated by Django 5.1.4 on 2026-05-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='自定义背景色'),
        ),
        migrations.AddField(
            model_name='worker',
            name='bg_mode',
            field=models.CharField(choices=[('none', '原图（不处理）'), ('white', '白底'), ('blue', '蓝底'), ('red', '红底'), ('rembg', '抠图后换色')], default='none', max_length=20, verbose_name='背景模式'),
        ),
    ]
