# Generated by Django 5.1.4 on 2026-05-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_add_bg_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工种')),
                ('responsibilities', models.TextField(blank=True, default='', verbose_name='岗位职责')),
            ],
            options={
                'verbose_name': '工种',
                'verbose_name_plural': '工种',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='worker',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='bg_mode',
        ),
    ]
