# Generated by Django 5.1.4 on 2026-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_jobtype_remove_worker_bg_color_remove_worker_bg_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='所属部门'),
        ),
    ]
