# Generated by Django 5.1.4 on 2026-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_worker_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
    ]
