# Generated by Django 5.1.4 on 2026-06-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_question_data_migration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tihao',
        ),
    ]
