# Generated by Django 5.1.4 on 2026-06-09 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_delete_tihao'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='info_submissions/', verbose_name='证件人像页')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='info_submissions/', verbose_name='证件国徽页')),
                ('one_inch_photo', models.ImageField(blank=True, null=True, upload_to='info_submissions/', verbose_name='一寸照片')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1\\d{10}$', message='请输入有效的手机号')], verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '公开信息提交',
                'verbose_name_plural': '公开信息提交',
                'ordering': ['-created_at'],
            },
        ),
    ]
