# Generated by Django 5.1.4 on 2026-06-09 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_infosubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosubmission',
            options={'verbose_name': '信息收集', 'verbose_name_plural': '信息收集记录'},
        ),
        migrations.AlterField(
            model_name='infosubmission',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1\\d{10}$')], verbose_name='手机号'),
        ),
    ]
