# Generated by Django 5.1.4 on 2026-06-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0038_alter_infosubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosubmission',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='infosubmission',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='infosubmission',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='infosubmission',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
