# Generated by Django 5.1.4 on 2026-06-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0039_add_info_collect_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, unique=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(default='888', max_length=128, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
    ]
