# Generated by Django 5.1.4 on 2026-06-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_alter_staff_id_number_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoSubmission',
        ),
    ]
