# Generated by Django 5.1.4 on 2026-06-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0040_alter_staff_id_number_alter_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosubmission',
            options={'ordering': ['-created_at'], 'verbose_name': '信息收集', 'verbose_name_plural': '信息收集记录'},
        ),
        migrations.AddField(
            model_name='question',
            name='analysis',
            field=models.TextField(blank=True, default='', verbose_name='解析'),
        ),
    ]
