# Generated by Django 5.1.4 on 2026-06-23 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0041_alter_infosubmission_options_question_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, verbose_name='所属章节'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_streak',
            field=models.IntegerField(default=0, verbose_name='正确连击数'),
        ),
        migrations.AddField(
            model_name='question',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='累计错误次数'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证号'),
        ),
        migrations.CreateModel(
            name='AnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('streak_before', models.IntegerField(verbose_name='答题前正确连击数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='答题时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_records', to='app01.question')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='问答内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app01.question')),
            ],
            options={
                'verbose_name': '题目笔记',
                'verbose_name_plural': '题目笔记',
                'ordering': ['-created_at'],
            },
        ),
    ]
